### ISSUE TITLE
Running from localhost public folder does not show proper page

### ISSUE THREAD

**Issue by tyeeman** [svandragt/carbon#17]
Like the above says I copied all files over to my localhost (Uwamp), and when I access http://localhost/carbon/public/ the page I get is http://localhost. Any tips?

**Comment by svandragt** [comment]
Hi tyeeman; Carbon did not support running from a subdirectory of a site. 
But now it does, download (or pull) the develop branch.

The only change you will have to make after you done this is to apply this patch:
[patch.diff.txt](https://github.com/svandragt/carbon/files/476594/patch.diff.txt)
All it does is adds tell the URL rewriter where index.php is relative to the site root.

**Comment by tyeeman** [comment]
How do I run the patch? I don't have git. Do I need it? Can I manually apply the patch?

**Comment by svandragt** [comment]
View it in notepad, the line starting with minus is changed into the line that starts with plus. 

Thanks, Sander
